stages:
  - docker
  - build
  - test
  - deploy

include:
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/version.gitlab-ci.yml
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/gradle.gitlab-ci.yml
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/docker.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# region Check

check:
  extends: [ .os.gradle ]
  needs: [ os.version ]
  stage: test

  script:
    - >
      ./gradlew check
      -PappVersion=$project_version

  interruptible: true

# endregion
# region Build & containerize

app:build:
  extends: [ .os.gradle ]
  needs: [ os.version ]
  stage: build

  script:
    - >
      ./gradlew app:distTar
      -PappVersion=$project_version
    - mv app/build/distributions/app-*.tar app.tar

  artifacts:
    paths:
      - app.tar

  interruptible: true

app:container:
  extends: [ .os.docker.build ]
  needs:
    - job: app:build
      artifacts: true
  stage: build

  variables:
    dockerfile: app/Dockerfile
    docker_context: app
    image: app

  interruptible: true

app:container:deploy:
  extends: [ .os.docker.rename ]
  needs: [ app:container, os.version ]
  stage: deploy

  variables:
    image: server

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        new_version: $project_version

  interruptible: false

# endregion
