# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test
  - deploy

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_PROTECTED
    - if: $CI_COMMIT_TAG

demo:web:build:
  needs: [ ]
  stage: build
  image: gradle:jdk17-focal

  script:
    - ./gradlew demo:jsProduction
    - mv build/js/packages/OpenSavvy-UI-demo/kotlin/dist dist-web

  artifacts:
    paths:
      - dist-web

  environment:
    name: review-demo/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/dist-web/index.html
    deployment_tier: development

dokka:
  needs: [ ]
  stage: build
  image: gradle:jdk17-focal

  script:
    - ./gradlew dokkaHtmlMultiModule
    - mkdir -p docs
    - mv build/dokka/htmlMultiModule docs

  artifacts:
    paths:
      - docs

  environment:
    name: review-documentation/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/docs/index.html
    deployment_tier: development

pages:
  image: alpine:latest
  stage: deploy
  needs:
    - job: demo:web:build
      artifacts: true
    - job: dokka
      artifacts: true
  script:
    - mkdir -p public/demo public/documentation
    - mv dist-web/* public/demo
    - mv docs/* public/documentation
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
