# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - docker
  - build
  - test
  - deploy

include:
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/docker.gitlab-ci.yml
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/gradle.gitlab-ci.yml
  - remote: https://gitlab.com/opensavvy/ci-templates/-/raw/main/version.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# Build the necessary images

chromium:build:
  extends: [ .os.docker.build ]
  needs: [ ]
  stage: docker

  variables:
    dockerfile: .gitlab/ci/chromium.dockerfile
    context: .gitlab/ci
    image: chromium

  interruptible: true

chromium:publish:
  extends: [ .os.docker.rename ]
  needs: [ chromium:build ]
  stage: deploy

  variables:
    image: chromium

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

  interruptible: true

android-sdk:build:
  extends: [ .os.docker.build ]
  needs: [ ]
  stage: docker

  variables:
    dockerfile: .gitlab/ci/android.dockerfile
    context: .gitlab/ci
    image: android-sdk

  interruptible: true

android-sdk:publish:
  extends: [ .os.docker.rename ]
  needs: [ android-sdk:build ]
  stage: deploy

  variables:
    image: android-sdk

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

  interruptible: true

# Tests

jvm:test:
  extends: [ .os.gradle ]
  needs: [ os.version ]
  stage: test

  script:
    - >
      ./gradlew
      jvmTest
      demo:desktop:test
      -PappVersion=$project_version

  interruptible: true

web:test:
  extends: [ .os.gradle ]
  needs: [ chromium:build, os.version ]
  stage: test
  image: $CI_REGISTRY_IMAGE/chromium:build-$CI_PIPELINE_IID

  script:
    - >
      ./gradlew
      jsBrowserTest
      -PappVersion=$project_version

  interruptible: true

android:test:
  extends: [ .os.gradle ]
  needs: [ android-sdk:build, os.version ]
  image: $CI_REGISTRY_IMAGE/android-sdk:build-$CI_PIPELINE_IID
  stage: test

  script:
    - >
      ./gradlew
      demo:android:test
      -PappVersion=$project_version

  artifacts:
    reports:
      junit: demo/android/build/test-results/*/*.xml
  interruptible: true

android:lint:
  extends: [ .os.gradle ]
  needs: [ android-sdk:build, os.version ]
  image: $CI_REGISTRY_IMAGE/android-sdk:build-$CI_PIPELINE_IID
  stage: test

  script:
    - ./gradlew lint -PappVersion=$project_version

  artifacts:
    paths:
      - demo/android/build/reports/
  interruptible: true

# Build the demo

demo:web:build:
  extends: [ .os.gradle ]
  needs: [ os.version ]
  stage: build

  script:
    - ./gradlew demo:web:production -PappVersion=$project_version
    - mv build/js/packages/Decouple-web/kotlin/dist dist-web

  artifacts:
    paths:
      - dist-web

  environment:
    name: review/$CI_COMMIT_REF_SLUG/demo
    url: https://$CI_PROJECT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/dist-web/index.html
    deployment_tier: development

demo:android:build:
  extends: [ .os.gradle ]
  needs: [ android-sdk:build, os.version ]
  image: $CI_REGISTRY_IMAGE/android-sdk:build-$CI_PIPELINE_IID
  stage: build

  script:
    - ./gradlew demo:android:assembleDebug -PappVersion=$project_version
    - mv demo/android/build/outputs/apk/debug/android-debug.apk demo-debug.apk

  artifacts:
    paths:
      - demo-debug.apk
    expose_as: Android App - Debug
  interruptible: true

dokka:
  extends: [ .os.gradle ]
  needs: [ android-sdk:build, os.version ]
  image: $CI_REGISTRY_IMAGE/android-sdk:build-$CI_PIPELINE_IID
  stage: build

  script:
    - ./gradlew dokkaHtmlMultiModule -PappVersion=$project_version
    - mkdir -p docs
    - mv build/dokka/htmlMultiModule/* docs

  artifacts:
    paths:
      - docs

  environment:
    name: review/$CI_COMMIT_REF_SLUG/documentation
    url: https://$CI_PROJECT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/docs/index.html
    deployment_tier: development

publish:
  extends: [ .os.gradle ]
  needs: [ jvm:test, web:test, os.version ]
  stage: deploy

  script:
    - >
      ./gradlew
      core:publishAllPublicationsToGitLabRepository
      style:material:publishAllPublicationsToGitLabRepository
      style:material-common:publishAllPublicationsToGitLabRepository
      style:material-tailwind:publishToGitLabRepository
      -PappVersion=$project_version

  rules:
    - if: $CI_COMMIT_TAG
  interruptible: false

telegram:
  stage: deploy
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ jvm:test, web:test ]

  script:
    - git changelog --format telegram-html --incoming >changelog
    - announce-telegram changelog "$CHAT_IDS"

  rules:
    - if: $BOT_TOKEN == null
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  interruptible: false

pages:
  image: alpine:latest
  stage: deploy
  needs:
    - job: demo:web:build
      artifacts: true
    - job: dokka
      artifacts: true
  script:
    - mkdir -p public/demo public/documentation
    - mv dist-web/* public/demo
    - mv docs/* public/documentation
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
  interruptible: false
