# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml

demo:web:build:
  needs: [ ]
  stage: build
  image: gradle:jdk17-focal

  script:
    - ./gradlew demo:jsProduction
    - mv build/js/packages/OpenSavvy-UI-demo/kotlin/dist dist-web

  artifacts:
    paths:
      - dist-web

  environment:
    name: review-demo/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/dist-web/index.html
    deployment_tier: development
