[versions]
# region Playground
kotlin = "1.9.10"
dokkatoo = "2.0.0"
# endregion

[plugins]
# region Playground
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokkatoo = { id = "dev.adamko.dokkatoo-html", version.ref = "dokkatoo" }
# endregion

[libraries]
# region Playground
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
# endregion

# To use existing plugins in convention plugins, we must also declare them as libraries
# region Playground
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.3.0" }
gradle-dokkatoo = { module = "dev.adamko.dokkatoo:dokkatoo-plugin", version.ref = "dokkatoo" }
# endregion
