[versions]
kotlin = "1.7.20"
dokka = "1.7.20"
android = "7.3.1"
pedestal = "1.0.1"

compose = "1.2.2"
compose-androidCompilerExtension = "1.3.2"

kotlinx-coroutines = "1.6.4"
kotlinx-datetime = "0.4.0"

androidx-core = "1.8.0"
androidx-lifecycle = "2.6.0"
androidx-activity = "1.5.1"
androidx-compose = "2023.01.00"
androidx-espresso = "3.4.0"

npm-postcss = "8.4.19"
npm-postcssLoader = "7.0.1"
npm-autoprefixer = "10.4.13"
npm-tailwindcss = "3.2.4"
npm-vite = "3.2.4"
npm-vite-commonJs = "1.0.3"
npm-rollup-commonJs = "23.0.2"
npm-roboto = "4.5.8"

[plugins]
kotlin = { id = "opensavvy.kotlin", version = "unspecified" }
kotlinJs = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMpp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

compose = { id = "org.jetbrains.compose", version.ref = "compose" }

android = { id = "opensavvy.android", version = "unspecified" }
androidLibrary = { id = "com.android.library", version.ref = "android" }
androidApplication = { id = "com.android.application", version.ref = "android" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-jvm = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

pedestal-state = { module = "opensavvy:state", version.ref = "pedestal" }
pedestal-logger = { module = "opensavvy:logger", version.ref = "pedestal" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-uiGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-windowSize = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }

gradle-gitVersion = { module = "com.palantir.gradle.gitversion:gradle-git-version", version = "0.15.0" }
gradle-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android" }

[bundles]
