# List of dependencies of the project

[versions]
pedestal = "2.1.0"

[plugins]

[libraries]
pedestal-progress = { module = "dev.opensavvy.pedestal:progress", version.ref = "pedestal" }
pedestal-progress-coroutines = { module = "dev.opensavvy.pedestal:progress-coroutines", version.ref = "pedestal" }

[bundles]
