
mkdocs:
  image:
    name: squidfunk/mkdocs-material
    entrypoint: [ "/bin/sh", "-c" ]
  stage: build

  before_script:
    - cd docs/website
    - ls

  script:
    - pwd
    - mkdocs build --site-dir ../../docs-website

  after_script:
    - echo "URL=$(.gitlab/ci/review-url.sh docs-website/index.html)" >>docs.env

  artifacts:
    paths:
      - docs-website
    reports:
      dotenv: docs.env

  environment:
    name: review/$CI_COMMIT_REF_SLUG/docs
    url: $URL
    deployment_tier: development
